version: '3.8'

services:
  # 1. START THE DATABASE SERVICE
  db:
    image: postgres:15-alpine
    container_name: job_db_container
    environment:
      POSTGRES_USER: ${DB_USER}      # .env
      POSTGRES_PASSWORD: ${DB_PASSWORD} # .env
      POSTGRES_DB: ${DB_NAME}        # .env
    volumes: # We created a volume to not lose our data when the container is deleted.
      - pg_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"

  # 2. START THE AUTOMATION SERVICE (main.py)
  scraper:
    build: .
    container_name: job_scraper_container
    command: python main.py
    depends_on:
      - db
    env_file:
      - .env
    environment:
      # In Docker 'db' is used instead of 'localhost'
      DATABASE_URL: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
    volumes:
      - .:/app

  # 3. START THE DASHBOARD SERVICE
  dashboard:
    build: .
    container_name: job_dashboard_container
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - db
    ports:
      - "8501:8501"
    environment:
      DATABASE_URL: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
    volumes:
      - .:/app

volumes:
  pg_data: